### PR TITLE
Apply ocamlformat.0.26.0

### PR DESCRIPTION
**Pull request by dinosaure**
A gently upgrade to use `ocamlformat.0.26.0`.

### CODE REVIEW

**Comment by dinosaure** [comment]
Note that currently the code does not compile but I have a patch which fix some `Lwt.catch` in the client application.

**Comment by hannesm** [comment]
would you mind to put that rev into a new `.git-blame-ignore-revs` file at the root (see https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view)

Also, I wonder why OCaml CI doesn't run here... maybe we should setup a simple GitHub action or cirrus CI?

**Comment by dinosaure** [comment]
About `ocaml-ci`, it's related to https://github.com/ocurrent/ocaml-ci/pull/867

**Comment by hannesm** [comment]
build has been fixed in #66, please rebase and add the git-blame-ignore-revs file :) thanks!

**Comment by dinosaure** [comment]
This PR was rebased :+1:.

**Comment by hannesm** [comment]
thanks, I added a .git-blame-ignore-revs file myself, pushed, and merged.

**Pull request merged**
